import fs from 'node:fs';
import path from 'node:path';
import { test, expect } from './helpers/test';
import { dist, variants } from './helpers/data';

const MIN_BYTES = 5_000;
const MAX_PAGES = 2;

// Chromium writes one "/Type /Page" object per page ("/Type /Pages" is the page tree).
const countPages = (pdf: Buffer) => (pdf.toString('latin1').match(/\/Type\s*\/Page(?![s\w])/g) ?? []).length;

for (const variant of variants) {
  const file = `steve-johnson-resume-${variant.id}.pdf`;

  test.describe(`PDF for "${variant.id}"`, () => {
    test('was generated by the build', () => {
      const onDisk = path.join(dist, 'resume', file);
      expect(fs.existsSync(onDisk), `${onDisk} is missing`).toBe(true);
      expect(fs.statSync(onDisk).size).toBeGreaterThan(MIN_BYTES);
    });

    test('is served as a real PDF with a sensible page count', async ({ request }) => {
      const response = await request.get(`/resume/${file}`);
      expect(response.status()).toBe(200);
      expect(response.headers()['content-type']).toContain('application/pdf');

      const body = await response.body();
      expect(body.subarray(0, 5).toString()).toBe('%PDF-');
      expect(body.length).toBeGreaterThan(MIN_BYTES);

      const pages = countPages(body);
      expect(pages, `${file} has ${pages} pages`).toBeGreaterThanOrEqual(1);
      expect(pages, `${file} has ${pages} pages`).toBeLessThanOrEqual(MAX_PAGES);
    });
  });
}
